### ISSUE TITLE
Berlin - Error from (presumably) placeholder data?

### ISSUE THREAD

**Issue by shinyfoil** [geometry-labs/icon-governance#18]
Worker is failing while processing messages. It looks like it's trying to get p-rep details from placeholder data since this is a testnet and valid data doesn't really matter.

In below example, it's trying to connect to `nodehx9eec61296a7010c867ce24c20e69588e28321124.example.com`, but that very obviously doesn't exist.

```
{'timestamp': 1641223131.568167, 'message': 'msg count 10000 and block 638197 for consumer group berlin-governance-consumer-group-head'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2[] Name or service not known
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f56c44fce20>: Failed to establish a new connection: [Errno -2[] Name or service not known
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nodehx9eec61296a7010c867ce24c20e69588e28321124.example.com', port=443): Max retries exceeded with url: /details (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f56c44fce20>: Failed to establish a new connection: [Errno -2[] Name or service not known'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/icon_governance/main_worker.py", line 74, in <module>
    main(args.worker_type)
  File "/opt/icon_governance/main_worker.py", line 33, in main
    transactions_worker_head()
  File "/opt/icon_governance/workers/transactions.py", line 164, in transactions_worker_head
    kafka.start()
  File "/opt/icon_governance/workers/kafka.py", line 181, in start
    self.process(msg)
  File "/opt/icon_governance/workers/transactions.py", line 62, in process
    details = get_details(params["details"[])
  File "/opt/icon_governance/utils/details.py", line 5, in get_details
    r = requests.get(details_endpoint)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nodehx9eec61296a7010c867ce24c20e69588e28321124.example.com', port=443): Max retries exceeded with url: /details (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f56c44fce20>: Failed to establish a new connection: [Errno -2[] Name or service not known'))
```

**Comment by robcxyz** [comment]
Needed to fix CI pipeline which goes for all services and will need a backfill likely
